# ref: https://docs.codecov.com/docs/codecovyml-reference
coverage:
  range: 90..100
  round: down
  precision: 1
  status:
    # ref: https://docs.codecov.com/docs/commit-status
    project:
      default:
        # Avoid false negatives
        threshold: 1%
    patch:
      default:
        target: auto
        # Avoid false negatives
        threshold: 1%
        base: auto 
        only_pulls: true

ignore:
  - "**/test_utils/*"
  - "**/test_utils*"
  - "**/test_util*"
  - "**/tests*"
  - "bin/"
  - "crates/derive/src/test_utils" # Ignore all files in test util directories
  - "crates/providers-alloy/src/alloy_providers.rs"  # Flaky testing with online providers
  - "crates/providers-alloy/src/beacon_client.rs"  # Flaky testing with online providers
  - "crates/mpt/src/noop.rs" # Uncovered noop implementations used downstream and by tests

# Make comments less noisy
comment:
  layout: "condensed_header, condensed_files, condensed_footer"
  require_changes: true
  hide_project_coverage: false
